server:
  port: 8084

spring:
  application:
    name: notification-service
  cloud:
    vault:
      enabled: false
    compatibility-verifier:
      enabled: false
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: local-access-key
        secret-key: local-secret-key
      sqs:
        endpoint: http://localhost:9324
  jackson:
    serialization:
      write-dates-as-timestamps: false
  mail:
    host: localhost
    port: 1025
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  endpoint:
    health:
      show-details: always

seatlock:
  notifications:
    queue-name: seatlock-events
    from-address: noreply@seatlock.local
    default-recipient: notifications@seatlock.local
